#!/bin/sh
set -e -x
git --version
upstream=$1
: ${upstream:=origin}
: ${REPO:=https://github.com/cataska/lovelycatherine.git}
git fetch $upstream
if [ `git rev-list HEAD...$upstream/master --count` -ne 0 ]; then
  echo "not deploying"
  exit 1
fi

rm -rf _public
git clone $REPO -b gh-pages _public

REV=`git describe --always`
cd _public
cp -R ../index.html ../css ../img ../js ../vendor .
git add -A .
echo "regen for $REV" | git commit-tree `git write-tree` -p `git rev-parse HEAD` -p $REV | xargs git reset --hard
git push origin gh-pages
cd ..
